# Generated by Django 4.2.6 on 2023-10-16 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    'modified_at',
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quizes',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    'modified_at',
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                (
                    'order',
                    models.PositiveSmallIntegerField(verbose_name='order'),
                ),
                (
                    'question',
                    models.CharField(max_length=256, verbose_name='question'),
                ),
                (
                    'quiz',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='questions',
                        to='core.quiz',
                        verbose_name='quiz',
                    ),
                ),
            ],
            options={
                'verbose_name': 'quiz question',
                'verbose_name_plural': 'quiz questions',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionChoice',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    'modified_at',
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                (
                    'order',
                    models.PositiveSmallIntegerField(verbose_name='order'),
                ),
                (
                    'answer',
                    models.CharField(max_length=256, verbose_name='answer'),
                ),
                (
                    'answer_slug',
                    models.CharField(
                        max_length=30, verbose_name='answer_slug'
                    ),
                ),
                (
                    'quiz_question',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='choices',
                        to='core.quizquestion',
                        verbose_name='quiz question',
                    ),
                ),
            ],
            options={
                'verbose_name': 'quiz question choice',
                'verbose_name_plural': 'quiz questions choice',
            },
        ),
        migrations.CreateModel(
            name='QuizAnswerSession',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    'modified_at',
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                (
                    'email',
                    models.EmailField(max_length=254, verbose_name='email'),
                ),
                ('answer_data', models.JSONField(verbose_name='answer data')),
                (
                    'quiz',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='answers',
                        to='core.quiz',
                        verbose_name='quiz',
                    ),
                ),
            ],
            options={
                'verbose_name': 'quiz answer session',
                'verbose_name_plural': 'quiz answer sessions',
            },
        ),
    ]
